

export const regions = [
    { code: "AF", name: "Afghanistan", numberCode: "+93" },
    { code: "AL", name: "Albania", numberCode: "+355" },
    { code: "DZ", name: "Algeria", numberCode: "+213" },
    { code: "AD", name: "Andorra", numberCode: "+376" },
    { code: "AO", name: "Angola", numberCode: "+244" },
    { code: "AG", name: "Antigua and Barbuda", numberCode: "+1-268" },
    { code: "AR", name: "Argentina", numberCode: "+54" },
    { code: "AM", name: "Armenia", numberCode: "+374" },
    { code: "AU", name: "Australia", numberCode: "+61" },
    { code: "AT", name: "Austria", numberCode: "+43" },
    { code: "AZ", name: "Azerbaijan", numberCode: "+994" },
    { code: "BS", name: "Bahamas", numberCode: "+1-242" },
    { code: "BH", name: "Bahrain", numberCode: "+973" },
    { code: "BD", name: "Bangladesh", numberCode: "+880" },
    { code: "BB", name: "Barbados", numberCode: "+1-246" },
    { code: "BY", name: "Belarus", numberCode: "+375" },
    { code: "BE", name: "Belgium", numberCode: "+32" },
    { code: "BZ", name: "Belize", numberCode: "+501" },
    { code: "BJ", name: "Benin", numberCode: "+229" },
    { code: "BT", name: "Bhutan", numberCode: "+975" },
    { code: "BO", name: "Bolivia", numberCode: "+591" },
    { code: "BA", name: "Bosnia and Herzegovina", numberCode: "+387" },
    { code: "BW", name: "Botswana", numberCode: "+267" },
    { code: "BR", name: "Brazil", numberCode: "+55" },
    { code: "BN", name: "Brunei", numberCode: "+673" },
    { code: "BG", name: "Bulgaria", numberCode: "+359" },
    { code: "BF", name: "Burkina Faso", numberCode: "+226" },
    { code: "BI", name: "Burundi", numberCode: "+257" },
    { code: "CV", name: "Cabo Verde", numberCode: "+238" },
    { code: "KH", name: "Cambodia", numberCode: "+855" },
    { code: "CM", name: "Cameroon", numberCode: "+237" },
    { code: "CA", name: "Canada", numberCode: "+1" },
    { code: "CF", name: "Central African Republic", numberCode: "+236" },
    { code: "TD", name: "Chad", numberCode: "+235" },
    { code: "CL", name: "Chile", numberCode: "+56" },
    { code: "CN",  name: "China", numberCode: "+86" },
    { code: "CO", name: "Colombia", numberCode: "+57" },
    { code: "KM", name: "Comoros", numberCode: "+269" },
    { code: "CG", name: "Congo", numberCode: "+242" },
    { code: "CD", name: "Congo (DRC)", numberCode: "+243" },
    { code: "CR", name: "Costa Rica", numberCode: "+506" },
    { code: "HR", name: "Croatia", numberCode: "+385" },
    { code: "CU", name: "Cuba", numberCode: "+53" },
    { code: "CY", name: "Cyprus", numberCode: "+357" },
    { code: "CZ", name: "Czech Republic", numberCode: "+420" },
    { code: "DK", name: "Denmark", numberCode: "+45" },
    { code: "DJ", name: "Djibouti", numberCode: "+253" },
    { code: "DM", name: "Dominica", numberCode: "+1-767" },
    { code: "DO", name: "Dominican Republic", numberCode: "+1-809" },
    { code: "EC", name: "Ecuador", numberCode: "+593" },
    { code: "EG", name: "Egypt", numberCode: "+20" },
    { code: "SV", name: "El Salvador", numberCode: "+503" },
    { code: "GQ", name: "Equatorial Guinea", numberCode: "+240" },
    { code: "ER", name: "Eritrea", numberCode: "+291" },
    { code: "EE", name: "Estonia", numberCode: "+372" },
    { code: "SZ", name: "Eswatini", numberCode: "+268" },
    { code: "ET", name: "Ethiopia", numberCode: "+251" },
    { code: "FJ", name: "Fiji", numberCode: "+679" },
    { code: "FI", name: "Finland", numberCode: "+358" },
    { code: "FR", name: "France", numberCode: "+33" },
    { code: "GA", name: "Gabon", numberCode: "+241" },
    { code: "GM", name: "Gambia", numberCode: "+220" },
    { code: "GE", name: "Georgia", numberCode: "+995" },
    { code: "DE", name: "Germany", numberCode: "+49" },
    { code: "GH", name: "Ghana", numberCode: "+233" },
    { code: "GR", name: "Greece", numberCode: "+30" },
    { code: "GD", name: "Grenada", numberCode: "+1-473" },
    { code: "GT", name: "Guatemala", numberCode: "+502" },
    { code: "GN", name: "Guinea", numberCode: "+224" },
    { code: "GW", name: "Guinea-Bissau", numberCode: "+245" },
    { code: "GY", name: "Guyana", numberCode: "+592" },
    { code: "HT", name: "Haiti", numberCode: "+509" },
    { code: "HN", name: "Honduras", numberCode: "+504" },
    { code: "HU", name: "Hungary", numberCode: "+36" },
    { code: "IS", name: "Iceland", numberCode: "+354" },
    { code: "IN", name: "India", numberCode: "+91" },
    { code: "ID", name: "Indonesia", numberCode: "+62" },
    { code: "IR", name: "Iran", numberCode: "+98" },
    { code: "IQ", name: "Iraq", numberCode: "+964" },
    { code: "IE", name: "Ireland", numberCode: "+353" },
    { code: "IL", name: "Israel", numberCode: "+972" },
    { code: "IT", name: "Italy", numberCode: "+39" },
    { code: "JM", name: "Jamaica", numberCode: "+1-876" },
    { code: "JP", name: "Japan", numberCode: "+81" },
    { code: "JO", name: "Jordan", numberCode: "+962" },
    { code: "KZ", name: "Kazakhstan", numberCode: "+7" },
    { code: "KE", name: "Kenya", numberCode: "+254" },
    { code: "KI", name: "Kiribati", numberCode: "+686" },
    { code: "KP", name: "North Korea", numberCode: "+850" },
    { code: "KR", name: "South Korea", numberCode: "+82" },
    { code: "KW", name: "Kuwait", numberCode: "+965" },
    { code: "KG", name: "Kyrgyzstan", numberCode: "+996" },
    { code: "LA", name: "Laos", numberCode: "+856" },
    { code: "LV", name: "Latvia", numberCode: "+371" },
    { code: "LB", name: "Lebanon", numberCode: "+961" },
    { code: "LS", name: "Lesotho", numberCode: "+266" },
    { code: "LR", name: "Liberia", numberCode: "+231" },
    { code: "LY", name: "Libya", numberCode: "+218" },
    { code: "LI", name: "Liechtenstein", numberCode: "+423" },
    { code: "LT", name: "Lithuania", numberCode: "+370" },
    { code: "LU", name: "Luxembourg", numberCode: "+352" },
    { code: "MG", name: "Madagascar", numberCode: "+261" },
    { code: "MW", name: "Malawi", numberCode: "+265" },
    { code: "MY", name: "Malaysia", numberCode: "+60" },
    { code: "MV", name: "Maldives", numberCode: "+960" },
    { code: "ML", name: "Mali", numberCode: "+223" },
    { code: "MT", name: "Malta", numberCode: "+356" },
    { code: "MH", name: "Marshall Islands", numberCode: "+692" },
    { code: "MR", name: "Mauritania", numberCode: "+222" },
    { code: "MU", name: "Mauritius", numberCode: "+230" },
    { code: "MX", name: "Mexico", numberCode: "+52" },
    { code: "FM", name: "Micronesia", numberCode: "+691" },
    { code: "MD", name: "Moldova", numberCode: "+373" },
    { code: "MC", name: "Monaco", numberCode: "+377" },
    { code: "MN", name: "Mongolia", numberCode: "+976" },
    { code: "ME", name: "Montenegro", numberCode: "+382" },
    { code: "MA", name: "Morocco", numberCode: "+212" },
    { code: "MZ", name: "Mozambique", numberCode: "+258" },
    { code: "MM", name: "Myanmar", numberCode: "+95" },
    { code: "NA", name: "Namibia", numberCode: "+264" },
    { code: "NR", name: "Nauru", numberCode: "+674" },
    { code: "NP", name: "Nepal", numberCode: "+977" },
    { code: "NL", name: "Netherlands", numberCode: "+31" },
    { code: "NZ", name: "New Zealand", numberCode: "+64" },
    { code: "NI", name: "Nicaragua", numberCode: "+505" },
    { code: "NE", name: "Niger", numberCode: "+227" },
    { code: "NG", name: "Nigeria", numberCode: "+234" },
    { code: "MK", name: "North Macedonia", numberCode: "+389" },
    { code: "NO", name: "Norway", numberCode: "+47" },
    { code: "OM", name: "Oman", numberCode: "+968" },
    { code: "PK", name: "Pakistan", numberCode: "+92" },
    { code: "PW", name: "Palau", numberCode: "+680" },
    { code: "PA", name: "Panama", numberCode: "+507" },
    { code: "PG", name: "Papua New Guinea", numberCode: "+675" },
    { code: "PY", name: "Paraguay", numberCode: "+595" },
    { code: "PE", name: "Peru", numberCode: "+51" },
    { code: "PH", name: "Philippines", numberCode: "+63" },
    { code: "PL", name: "Poland", numberCode: "+48" },
    { code: "PT", name: "Portugal", numberCode: "+351" },
    { code: "QA", name: "Qatar", numberCode: "+974" },
    { code: "RO", name: "Romania", numberCode: "+40" },
    { code: "RU", name: "Russia", numberCode: "+7" },
    { code: "RW", name: "Rwanda", numberCode: "+250" },
    { code: "KN", name: "Saint Kitts and Nevis", numberCode: "+1-869" },
    { code: "LC", name: "Saint Lucia", numberCode: "+1-758" },
    { code: "VC", name: "Saint Vincent and the Grenadines", numberCode: "+1-784" },
    { code: "WS", name: "Samoa", numberCode: "+685" },
    { code: "SM", name: "San Marino", numberCode: "+378" },
    { code: "ST", name: "Sao Tome and Principe", numberCode: "+239" },
    { code: "SA", name: "Saudi Arabia", numberCode: "+966" },
    { code: "SN", name: "Senegal", numberCode: "+221" },
    { code: "RS", name: "Serbia", numberCode: "+381" },
    { code: "SC", name: "Seychelles", numberCode: "+248" },
    { code: "SL", name: "Sierra Leone", numberCode: "+232" },
    { code: "SG", name: "Singapore", numberCode: "+65" },
    { code: "SK", name: "Slovakia", numberCode: "+421" },
    { code: "SI", name: "Slovenia", numberCode: "+386" },
    { code: "SB", name: "Solomon Islands", numberCode: "+677" },
    { code: "SO", name: "Somalia", numberCode: "+252" },
    { code: "ZA", name: "South Africa", numberCode: "+27" },
    { code: "SS", name: "South Sudan", numberCode: "+211" },
    { code: "ES", name: "Spain", numberCode: "+34" },
    { code: "LK", name: "Sri Lanka", numberCode: "+94" },
    { code: "SD", name: "Sudan", numberCode: "+249" },
    { code: "SR", name: "Suriname", numberCode: "+597" },
    { code: "SZ", name: "Swaziland", numberCode: "+268" },
    { code: "SE", name: "Sweden", numberCode: "+46" },
    { code: "CH", name: "Switzerland", numberCode: "+41" },
    { code: "SY", name: "Syria", numberCode: "+963" },
    { code: "TW", name: "Taiwan", numberCode: "+886" },
    { code: "TJ", name: "Tajikistan", numberCode: "+992" },
    { code: "TZ", name: "Tanzania", numberCode: "+255" },
    { code: "TH", name: "Thailand", numberCode: "+66" },
    { code: "TL", name: "Timor-Leste", numberCode: "+670" },
    { code: "TG", name: "Togo", numberCode: "+228" },
    { code: "TK", name: "Tokelau", numberCode: "+690" },
    { code: "TO", name: "Tonga", numberCode: "+676" },
    { code: "TT", name: "Trinidad and Tobago", numberCode: "+1-868" },
    { code: "TN", name: "Tunisia", numberCode: "+216" },
    { code: "TR", name: "Turkey", numberCode: "+90" },
    { code: "TM", name: "Turkmenistan", numberCode: "+993" },
    { code: "TV", name: "Tuvalu", numberCode: "+688" },
    { code: "UG", name: "Uganda", numberCode: "+256" },
    { code: "UA", name: "Ukraine", numberCode: "+380" },
    { code: "AE", name: "United Arab Emirates", numberCode: "+971" },
    { code: "GB", name: "United Kingdom", numberCode: "+44" },
    { code: "US", name: "United States", numberCode: "+1" },
    { code: "UY", name: "Uruguay", numberCode: "+598" },
    { code: "UZ", name: "Uzbekistan", numberCode: "+998" },
    { code: "VU", name: "Vanuatu", numberCode: "+678" },
    { code: "VA", name: "Vatican City", numberCode: "+379" },
    { code: "VE", name: "Venezuela", numberCode: "+58" },
    { code: "VN", name: "Vietnam", numberCode: "+84" },
    { code: "YE", name: "Yemen", numberCode: "+967" },
    { code: "ZM", name: "Zambia", numberCode: "+260" },
    { code: "ZW", name: "Zimbabwe", numberCode: "+263" }
];